describe('diagnostics')
    .after(function(){
      BrowserCouch('test').wipe()
    })
    .should('give diagnostics', function(){
      var db = BrowserCouch('test')
      db.put({_id: '1', name: 'tom'})
      db.put({_id: '2', name: 'jam'})
      db.put({_id: '3', name: 'kelly'})
      db.put({_id: '4', name: 'scott'})
      db.put({_id: '5', name: 'mary'})
      db.put({_id: '6', name: 'jen'})
      db.del(db.get('6'))
      db.del(db.get('5'))
      var jan = db.get('2')
      jan.name = 'jan'
      db.put(jan)
      
      var diag = db.diagnostics()
      expect(diag.dbName).toBe('test')
      expect(diag.dbInfo.lastSeq).toBe(9)
      expect(diag.dbInfo.docCount).toBe(4)
      expect(diag.totalDocs).toBe(4)
      expect(diag.deletedDocs).toBe(2)
      expect(diag.allDocs.length).toBe(6)
      expect(diag.allDocs[0].doc).notToBe(undefined)
    })